### ISSUE TITLE
 The gyroscope is not working

### ISSUE THREAD

**Issue by AnByronV** [What-the-Flutter/VR-Player#10]
When I reproduce the example video. The player does not respond to the movement of the mobile device. Apparently it is not responding to the movement of the gyroscope, however it is possible to navigate the video using the finger.

**Comment by Harishsharma714** [comment]
I am also facing same issue could get solution of it?

**Comment by calinvasileandrei** [comment]
Same problem here for android, on ios it seems to looks fine.

**Comment by KirillSergeevich** [comment]
Thanks for your report!
We checked it for several devices and found that behavior differs for various devices. For example gyroscope handling works fine for Google Pixel 4, but doesn't work for Google Pixel 1.
If you have any idea how to fix it, please send a pull request.

**Comment by AnByronV** [comment]
I was using the same package a few months ago with the older version, and I hadn't problems using the gyroscope. However, after creating a new app with the latest version is when the gyro stopped working.
Note: I have tried using the new application with an older version of the package but the problem persists.

**Comment by yuvraj-commit** [comment]
Guys got any solution for this issue ?

**Comment by KirillSergeevich** [comment]
This issue should be fixed in v0.2.1
