### ISSUE TITLE
Not working on Android with MP4

### ISSUE THREAD

**Issue by nm-quins** [What-the-Flutter/VR-Player#33]
Player does not see MP4 video on Android, just black screen with error "Failed to initialize player engine". On iOS works just fine. Video — https://cdn.spoolapp.ru/videos/01.mp4

**Comment by nm-quins** [comment]
Also, we see error Attempt to invoke 'play()' on null instance of the player engine

**Comment by nm-quins** [comment]
Also, we tried convert video to m3u8. So, https://cdn.spoolapp.ru/videos/01.m3u8 doesn't work also (

**Comment by alesiaradkevich** [comment]
Hi! Could you please provide code samples for the last two errors?

**Comment by Azizrajflutter** [comment]
Video Not Play on Android Version 10
