### ISSUE TITLE
return `StatelessWidget` instead of a "Widget returning method" for `nativeView`

### ISSUE THREAD

**Issue by aytunch** [What-the-Flutter/VR-Player#4]
Is there a specific reason why `nativeView` is implemented as a function instead of a `StatelessWidget`?
Usually it is better practice not to return widgets for better performance.
https://github.com/flutterwtf/VR-Player/blob/0074f5df838981e804d6bb7d5a7f87de7e5f6e36/lib/vr_player.dart#L252

```
Widget nativeView() {
  ...
}
```

**Comment by temaand1** [comment]
I agree that it's usually better to return a `StatelessWidget`, but in this case it doesn't affect performance. It's simply done for better readability of the code
