### ISSUE TITLE
360º pictures functionality

### ISSUE THREAD

**Issue by emmanuel-montoya** [What-the-Flutter/VR-Player#7]
Could this work with 360º pictures? It would be really helpful to start social networks app concepts with VR

**Comment by temaand1** [comment]
@emmanuel-montoya Unfortunately, at the moment we only support working with videos. Perhaps we will think about adding this in future versions, or you can create a PR with this feature and we will be happy to add it to our player. Or you can try using [this](https://pub.dev/packages/panorama) package
